meta_product_name: "Simply Rest"
meta_title: "Simply Rest - la restauration n'a jamais été aussi technologique"
meta_description: "Un logiciel d'aide à la prise de décision"
meta_image: "logo.png" # should exist in `app/assets/images/`
